/**
 * Layer Mapping Configuration Types
 * Defines the multi-layer variable aliasing architecture
 */

/**
 * Mapping rule for transforming variables between layers
 */
export interface LayerMappingRule {
  id: string;
  sourcePattern: string;
  targetPattern: string;
  transformFunction?: string; // e.g., "step => step * 1.2"
  description?: string;
}

/**
 * Definition for a single layer in the variable architecture
 */
export interface LayerDefinition {
  id: string;
  order: number;
  collectionName: string;
  displayName: string;
  description: string;
  enabled: boolean;
  
  // Flag for auto-generated layers (e.g., Primitives from RangDe)
  isAutoGenerated?: boolean;
  
  // Naming patterns for variables in this layer
  namingPattern: string; // e.g., "{group}/{step}/{scale}"
  
  // What this layer aliases to (undefined for primitives)
  aliasesToLayer?: string; // Layer ID
  
  // How variables are generated
  generationType: 'primitives' | 'semantic' | 'contextual' | 'hierarchy' | 'state' | 'theme' | 'brand' | 'mode';
  
  // Modes for this collection (if multi-mode)
  modes?: string[];
  
  // Mapping rules for transformation
  mappingRules?: LayerMappingRule[];
  
  // Optional: Variable count estimate
  estimatedVariableCount?: number;
}

/**
 * Global rules for layer mapping behavior
 */
export interface LayerMappingGlobalRules {
  skipMissingLayers: boolean;
  validateContrast: boolean;
  allowCircularRefs: boolean;
  autoSyncPrimitives: boolean; // Auto-sync primitives from RangDe
}

/**
 * Complete layer mapping configuration
 */
export interface LayerMappingConfig {
  version: string;
  layers: LayerDefinition[];
  globalRules: LayerMappingGlobalRules;
  metadata?: {
    createdAt?: number;
    updatedAt?: number;
    author?: string;
    description?: string;
  };
}

/**
 * Default layer configuration matching OneUI Foundations architecture (9 core layers)
 */
export const DEFAULT_LAYER_CONFIG: LayerMappingConfig = {
  version: "1.0.0",
  layers: [
    {
      id: "primitives",
      order: 0,
      collectionName: "00_Primitives",
      displayName: "Primitives",
      description: "Auto-loaded from RangDe Colors tab (all palettes + steps)",
      enabled: true,
      isAutoGenerated: true,
      namingPattern: "{paletteName}/{step}/{scale}",
      generationType: "primitives",
      aliasesToLayer: undefined,
      estimatedVariableCount: 1920 // 10 palettes × 24 steps × 8 scales
    },
    {
      id: "semi-semantics",
      order: 1,
      collectionName: "00_Semi semantics",
      displayName: "Semi Semantics",
      description: "Step-based semantic groupings (Grey/2500/Surface)",
      enabled: true,
      namingPattern: "{group}/{step}/{scale}",
      generationType: "semantic",
      aliasesToLayer: "primitives",
      estimatedVariableCount: 192 // Grey scale: 24 steps × 8 scales
    },
    {
      id: "colour-mode",
      order: 2,
      collectionName: "02 Colour Mode",
      displayName: "Colour Mode",
      description: "Light/Dark theme variations",
      enabled: true,
      namingPattern: "{appearance}/{mode}",
      generationType: "mode",
      aliasesToLayer: "semi-semantics",
      modes: ["Light", "Dark"],
      estimatedVariableCount: 384 // 192 × 2 modes
    },
    {
      id: "appearance",
      order: 6,
      collectionName: "1 Appearance",
      displayName: "Appearance",
      description: "Contextual naming patterns",
      enabled: true,
      namingPattern: "{context}/{type}",
      generationType: "contextual",
      aliasesToLayer: "interaction-state",
      modes: ["Neutral", "Primary", "Secondary", "Sparkle", "Positive", "Negative", "Warning", "Informative", "Brand BG"],
      estimatedVariableCount: 128
    },
    {
      id: "fill-emphasis",
      order: 4,
      collectionName: "2 Fill emphasis",
      displayName: "Fill Emphasis",
      description: "Visual hierarchy levels",
      enabled: true,
      namingPattern: "{emphasis}/{variant}",
      generationType: "hierarchy",
      aliasesToLayer: "background-level",
      modes: ["Ghost", "Minimal", "Subtle", "Bold"],
      estimatedVariableCount: 96
    },
    {
      id: "background-level",
      order: 3,
      collectionName: "3 Background Level",
      displayName: "Background Level",
      description: "Surface stacking system",
      enabled: true,
      namingPattern: "{level}/{surface}",
      generationType: "hierarchy",
      aliasesToLayer: "colour-mode",
      modes: ["Level 0", "Level 1", "Level 2", "Bold", "Elevated"],
      estimatedVariableCount: 64
    },
    {
      id: "interaction-state",
      order: 5,
      collectionName: "4 Interaction state",
      displayName: "Interaction State",
      description: "Interactive states (Hover/Press/Focus)",
      enabled: true,
      namingPattern: "{state}/{component}",
      generationType: "state",
      aliasesToLayer: "fill-emphasis",
      modes: ["Idle", "Hover", "Pressed", "Focus"],
      estimatedVariableCount: 192
    },
    {
      id: "theme",
      order: 7,
      collectionName: "9 Theme",
      displayName: "Theme",
      description: "Brand themes (MyJio/JioFinance/JioHome)",
      enabled: true,
      namingPattern: "{brand}/{appearance}",
      generationType: "theme",
      aliasesToLayer: "appearance",
      modes: ["MyJio", "JioFinance", "JioHome"],
      estimatedVariableCount: 384 // 128 × 3 brands
    },
    {
      id: "brand",
      order: 8,
      collectionName: "10 Brand",
      displayName: "Brand",
      description: "Brand variants (Jio/JS)",
      enabled: true,
      namingPattern: "{brandVariant}/{token}",
      generationType: "brand",
      aliasesToLayer: "theme",
      modes: ["Jio", "JS"],
      estimatedVariableCount: 256 // 128 × 2 variants
    }
  ],
  globalRules: {
    skipMissingLayers: false,
    validateContrast: true,
    allowCircularRefs: false,
    autoSyncPrimitives: true
  },
  metadata: {
    createdAt: Date.now(),
    description: "OneUI Foundations 9-layer architecture (core layers)"
  }
};

/**
 * Helper function to get layer by ID
 */
export function getLayerById(config: LayerMappingConfig, layerId: string): LayerDefinition | undefined {
  return config.layers.find(l => l.id === layerId);
}

/**
 * Helper function to get enabled layers in order
 */
export function getEnabledLayers(config: LayerMappingConfig): LayerDefinition[] {
  return config.layers
    .filter(l => l.enabled)
    .sort((a, b) => a.order - b.order);
}

/**
 * Helper function to validate layer configuration
 */
export function validateLayerConfig(config: LayerMappingConfig): {
  valid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  // Check for duplicate orders
  const orders = config.layers.map(l => l.order);
  const duplicateOrders = orders.filter((order, index) => orders.indexOf(order) !== index);
  if (duplicateOrders.length > 0) {
    errors.push(`Duplicate layer orders found: ${duplicateOrders.join(', ')}`);
  }
  
  // Check for circular aliases
  const enabledLayers = getEnabledLayers(config);
  for (const layer of enabledLayers) {
    if (layer.aliasesToLayer) {
      const targetLayer = getLayerById(config, layer.aliasesToLayer);
      if (!targetLayer) {
        errors.push(`Layer "${layer.displayName}" aliases to non-existent layer "${layer.aliasesToLayer}"`);
      } else if (targetLayer.order >= layer.order) {
        errors.push(`Layer "${layer.displayName}" cannot alias to layer "${targetLayer.displayName}" (must alias to previous layer)`);
      }
    }
  }
  
  // Check if primitives layer exists and is enabled
  const primitivesLayer = config.layers.find(l => l.id === 'primitives');
  if (!primitivesLayer) {
    errors.push('Primitives layer is missing');
  } else if (!primitivesLayer.enabled) {
    warnings.push('Primitives layer is disabled - variable generation may fail');
  }
  
  return {
    valid: errors.length === 0,
    errors,
    warnings
  };
}

/**
 * Helper function to estimate total variable count
 */
export function estimateTotalVariables(config: LayerMappingConfig): number {
  return getEnabledLayers(config)
    .reduce((sum, layer) => sum + (layer.estimatedVariableCount || 0), 0);
}
